### ISSUE TITLE
CLI wrapping

### ISSUE THREAD

**Issue by N3xed** [TheCherno/Sparky#117]
I'm currently working on wrapping the Sparky code, beginning with:
- Window
- Application
- ...

If somebody is also wrapping the code, please leave a comment, so that we don't wrap the same code.
### Questions:
- When there is a getter for a specific variable, should this getter method be made into a property?

**Comment by Jacob-Mango** [comment]
The reason why know one has bothered creating one as of yet is because a CLI generator has been in the works. The CLI generator would be easier to use and maintain as it would read all the code and create a CLI wrapping based of what is available. This is all I know at the time being. It would be best to wait and see what happens. 

Other wise these repositories may be useful to you;
- https://github.com/TheCherno/Sparky/tree/cli 
- https://github.com/TheCherno/Sparky/tree/cligen

**Comment by N3xed** [comment]
Thank you for your answer, but I know that a CLI generator is in the works. Despite that TheCherno said in one of his last devlogs, that he'd appreciate the wrapping of the Sparky code, because he needs to know how the CLI generator should wrap the code, that it can't do yet.
