### ISSUE TITLE
Slider will not lose focus when releasing mouse outside of the window.

### ISSUE THREAD

**Issue by Linkaan** [TheCherno/Sparky#53]
I noticed when playing around with sparky that when using the debug menu if I released the mouse outside of the application window after I had clicked on the slider it would not release focus. Maybe it isn't relevant since it is only used for debugging right now.

**Comment by TheCherno** [comment]
No this is very much relevant, and is a bug. This happens with the window in general, not just the slider. You can easily replicate this if you use the mouse to move the camera (whilst holding down a mouse button and ALT in Test3D), drag the mouse outside the window, and release the mouse button. This will be fixed in the future.

**Comment by TheCherno** [comment]
Fixed in March 2016 release.
